apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: can2025_gold
    user: admin
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaleDB: false
    secureJsonData:
      password: "password123"
    isDefault: true
    editable: true
